
DROP DATABASE IF EXISTS pbr12f5yzuwdd3z4;

CREATE DATABASE pbr12f5yzuwdd3z4;
USE pbr12f5yzuwdd3z4;

CREATE TABLE burgers (
    id int NOT NULL AUTO_INCREMENT,
    burger_name varchar (100) NOT NULL,
    devoured BOOLEAN NOT NULL DEFAULT false,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)